### ISSUE TITLE
FFmpeg 5?

### ISSUE THREAD

**Issue by Allan-Nava** [FedericoCarboni/setup-ffmpeg#12]
It has the ffmpeg 5?

**Comment by GrandMoff100** [comment]
Yes, yes it does. Look at the README to see where they get their builds from. The latest version is 5.1.1 as I write this.

**Comment by FedericoCarboni** [comment]
The action is actually using ffmpeg version 5.0.1 right now (as I write this). It lags behind somewhat (it's actually a bug in the script that uploads the binaries, I'll fix it as soon as I have time). But yeah it uses ffmpeg 5, not exactly the latest version but still recent enough for most use case.
