### ISSUE TITLE
Action doesn't install FFmpeg 6

### ISSUE THREAD

**Issue by rob93c** [FedericoCarboni/setup-ffmpeg#13]
Hello all,
looking at [one of my recent action's logs](https://github.com/Stickerifier/Stickerify/actions/runs/5026941738/jobs/9015827240), I noticed that `setup-ffmpeg` still retrieves the version 5.0.1 of both FFmpeg and FFprobe.

After a quick look, I found that [the action to create a release](https://github.com/FedericoCarboni/setup-ffmpeg/blob/master/.github/workflows/builds.yml) has been failing since July 2022 and its most recent execution shows the following error:

> Run actions/create-release@v1
  with:
    tag_name: ffmpeg-6.0-
    release_name: FFmpeg Build v6.0
    draft: false
    prerelease: false
  env:
    GITHUB_TOKEN: ***
Error: Validation Failed: {"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not a valid tag"}, {"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not well-formed"}, {"resource":"Release","code":"custom","message":"Published releases must have a valid tag"}

Also, the action used internally ([`actions/create-release`](https://github.com/actions/create-release)) is not maintained anymore so it can be worth considering to replace it with one of its alternatives listed in [their README](https://github.com/actions/create-release#readme).

**Comment by FedericoCarboni** [comment]
I've been fairly busy recently, I'll try to fix this as soon as I can. If anyone has a fix, open a pull request and I'll merge it.
