### ISSUE TITLE
Often `Error: TypeError: fetch failed` errors

### ISSUE THREAD

**Issue by bramp** [FedericoCarboni/setup-ffmpeg#20]
I quite often get `Error: TypeError: fetch failed`, and it's not clear why the fetch failed.

So a request and a question

1) Can we get better error messages in this situation?

2) Why is the cache not being used (and thus avoiding a fetch)? and/or I don't see cache listed under https://github.com/bramp/ffmpeg-cli-wrapper/actions/caches

thanks

**Comment by bramp** [comment]
oh in case it helps: https://github.com/bramp/ffmpeg-cli-wrapper/actions/runs/8238926460/job/22531004547 and full log

```
1. Run FedericoCarboni/setup-ffmpeg@v3
2.  with:
3.     ffmpeg-version: release
4.    github-token: ***
5. Error: TypeError: fetch failed
```

**Comment by federicocarboni** [comment]
The `fetch` causing the  `TypeError` is needed to download the versions list from the upstream source (e.g. [johnvansickle.com](https://www.johnvansickle.com/ffmpeg/)). By default the latest stable release is installed, but it has to know what that version actually is before checking in the cache for a match.

Pinning ffmpeg to a specific version may mitigate the issue as it will check the cache directly, set `ffmpeg-version` to `6.1.0` for example. Though I'm still not sure what's causing this in #19 there are more details.

**Comment by bramp** [comment]
Ah sorry, some how I didn't notice #19 before filling this.

Thanks for the response! I'll close this in favour of #19.
