### ISSUE TITLE
404 when running this workflow step

### ISSUE THREAD

**Issue by DeepDiver1975** [FedericoCarboni/setup-ffmpeg#3]
![Screenshot from 2020-12-21 09-57-11](https://user-images.githubusercontent.com/1005065/102758344-eb6c2d00-4372-11eb-8e50-04767b30be98.png)

**Comment by FedericoCarboni** [comment]
It looks like the workflow that uploads FFmpeg builds to GitHub failed. It should work normally again now, but I'll have to make sure it doesn't happen again.

**Comment by DeepDiver1975** [comment]
no longer observed -> close
