### ISSUE TITLE
Rate limit exceeded error on macos

### ISSUE THREAD

**Issue by rluzuriaga** [FedericoCarboni/setup-ffmpeg#4]
I am trying to use this action in my project running both Windows and Mac jobs.
It was working before for both, but now it only works on the Windows jobs.

When running it on the Mac job, I get this error `Error: API rate limit exceeded for 199.7.166.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)`

**Comment by FedericoCarboni** [comment]
The action downloads the FFmpeg binaries from releases using the GitHub API.
IP addresses for GitHub-hosted macos machines in GitHub Actions don't change. Because of this, the action fails randomly on macos, adding a `token` option, which takes a GitHub token to authenticate requests to the GitHub API, should fix this.

**Comment by rluzuriaga** [comment]
Thank you for the quick response. I am still a bit new to GitHub Actions so maybe I am doing something wrong. This is what my step looks like after the change from you comment.
```
- name: Setup FFmpeg
  uses: FedericoCarboni/setup-ffmpeg@v1-beta
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
```

My job errors out saying: 
```
Warning: Unexpected input(s) 'token', valid inputs are ['']
Run FedericoCarboni/setup-ffmpeg@v1-beta
Error: API rate limit exceeded for 199.7.166.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

**Comment by FedericoCarboni** [comment]
Maybe I was a bit unclear, I still haven't added that token option. I will add it, and then I'll publish a new release (hopefully a more stable one). I am only one person and I don't have much time right now, but I hope I can fix this before the end of the week.

**Comment by rluzuriaga** [comment]
Oh I am so sorry I misunderstood your comment. Thank you for clearing that up.
